name: Upload File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Upload a file'
        required: true
        type: file

jobs:
  upload_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload file to repository
      run: |
        mkdir -p uploads
        echo "${{ github.event.inputs.file }}" > uploads/${{ github.event.inputs.file }}

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add uploads/*
        git commit -m "Uploaded file"
        git push
