name: Upload File Handler

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]YamkelaDev.noreply.github.com"

    - name: Check for uploads directory
      run: |
        if [ -d "uploads" ] && [ "$(ls -A uploads)" ]; then
          git add uploads/*
          git commit -m "New file uploaded"
          git push origin main
        else
          echo "No files to upload"
        fi
